---
repository:
  description: Devcontainer for LaTeX
  topics: vscode, codespaces, devcontainer, latex, latexmk, template, pdf, bibtex
  delete_branch_on_merge: true
  has_wiki: false
  private: false
